services:
    register_api:
        class: Micro\BaseServiceBundle\Services\API\RegisterService
        arguments: [@rest_client]
        
    rest_client:
        class: Micro\ClientBundle\Rest\Client
        arguments: [%registry_url%]
        
    configuration_api:
        class: Micro\BaseServiceBundle\Services\API\ConfigurationService
        arguments: [%micro_services%]