language: php
php:
- 5.6
- 5.5
- hhvm

before_script:
  - composer install --dev

script: ./vendor/bin/phpunit --coverage-text

before_install:
  - pip install --user codecov
after_success:
  - codecov
